### PR TITLE
data hash check.

### PR DESCRIPTION
**Pull request by qaydm1979**

### CODE REVIEW

**Comment by jdtheiss** [comment]
Unfortunately, we already have this in the dir_utils module as the "validate_data" function.

**Comment by qaydm1979** [comment]
What is still missing.

**Comment by jdtheiss** [comment]
I think we just need to work on the wrapper and probably a way to filter the data to remove the effect of the scanner drift.

**Comment by mlnewton** [comment]
We need a test for the wrapper. It would be great for that to get started.
I'm continuing on the wrapper itself and likely won't be able to finish both

**Comment by jdtheiss** [comment]
I'm going to close this since we already have the necessary functions. Perhaps we can raise issues for the wrapper testing and filter function.

**Pull request closed without merging**
