### PR TITLE
Adding problematic slice_timing update

### PR DESCRIPTION
**Pull request by joewiner**
I've cleaned up the slice timing code, but I'm getting an error here where the scipy interpolate function says "failed in converting 2nd argument `y' of dfitpack.fpcurf0 to C/Fortran array" - I'm guessing this has to do with the type of data being passed into the function? Can someone help out with this?

### CODE REVIEW

**Comment by jdtheiss** [comment]
Maybe it's related to the ellipsis on line 228 in the y numpy array.

**Comment by joewiner** [comment]
What do you mean?

**Comment by jdtheiss** [comment]
I think one of the values got cut off where it shows "...598247".

y = array([ 4.98692701,  5.17466505,  4.02527958,  5.25289685,  6.07630922,
        4.41108788,  2.3280561 ,  5.53387422, ...598247,  6.30956467,  5.23387126,  4.74728322,
        4.10174256,  5.05153159,  5.66132716,  6.95420657,  5.84020852])

**Comment by joewiner** [comment]
Where is this coming from? What y array?

**Comment by joewiner** [comment]
Oh ok  I see what you're referring to in Travis. I'm still not sure what's leading to that problem but I'll try to fix it.

**Comment by jdtheiss** [comment]
Never mind, I think that's just a red herring. I'm not sure what the issue is. Also unrelated, you have a comma after the "]" for time_offsets at line 29 of the slice_time_corr code.

**Comment by joewiner** [comment]
@matthew-brett any tips on this Fortran array conversion error?

**Comment by jdtheiss** [comment]
Would getting a negative value in the random data Y (from your test) cause an error?

**Comment by joewiner** [comment]
I don't think that is the problem, since it also failed when I tried it with a real file from the dataset

**Comment by jdtheiss** [comment]
Hmm, I'll take a look at it in person when we meet.

**Comment by joewiner** [comment]
Check out https://github.com/practical-neuroimaging/pna-utils/blob/master/slicetime.py - Matthew suggested using this for inspiration

**Comment by jdtheiss** [comment]
I'll fix the hrf test...

**Comment by mlnewton** [comment]
Is it an okay to merge this, Joe?

**Comment by joewiner** [comment]
No not yet I'd like to take a look at padding first

**Comment by joewiner** [comment]
I've changed the code back so it will pull slice timing info from the .json file. I'm not going to be able to add the padding info in time. I have read over the code but don't understand where the "pad" data is supposed to come from. If someone wants to merge this, I don't _think_ it will ruin everything...

**Comment by jdtheiss** [comment]
Since the code is based on the exercise from class, I think it should be fine the way it is currently written.

**Comment by joewiner** [comment]
Alright this is less of a mess than it appears - the way to fix this issue is to make the offset_times an input, and the wrapper code will grab the times from the .json file. I'm going to fix this script and the test to reflect these changes. @jdtheiss since you're working on it, could you add the following lines to the wrapper code (...and correct me if I'm wrong)?

data_file = dir_utils.search_directory(data_folder, 'task-visualimageryfalsememory_bold.json')
outputs = dir_utils.get_contents(data_file, ['SliceTiming'])
time_offsets = outputs[0]

then the wrapper should call slice timing like this:

time_corrected_data = fmri_utils.slice_timing_corr.slice_timing_corr(data, TR, time_offsets)

**Comment by jdtheiss** [comment]
Ok, great. That is what is implemented in the wrapper code. Thanks!

**Pull request merged**
