### PR TITLE
Updated model_signal and test to include t statistic function.

### PR DESCRIPTION
**Pull request by jdtheiss**
I've created a function within the model_signal module to allow for t-tests, and I've also updated the tests for the model_signal module as well.

### CODE REVIEW

**Comment by jdtheiss** [comment]
I don't understand why it won't let me edit the __init__.py file to reflect the new function.

**Comment by joewiner** [comment]
@matthew-brett can you help us out with this? Justin is having a conflict issue with the init.py file

**Comment by matthew-brett** [comment]
Justin - true this on your own machine:

```
git fetch origin   # presumably points to the main repo
git merge origin/master
```

This last should generate a merge conflict, that you fix, by editing files with the conflicts, to remove the conflict markers and choose the version that you want.  Then ``git add`` the changes you made and ``git commit`` to finish up the merge.   Now the history records that you've got the upstream changes already, so when you push this merged branch up here to the pull request interface, git will see that you've resolved the conflict.

See: https://bic-berkeley.github.io/psych-214-fall-2016/git_walk_through.html#conflicts

**Comment by jdtheiss** [comment]
Ok, thanks @matthew-brett.

**Comment by joewiner** [comment]
So @jdtheiss's  latest commit passed the test but failed after I merged it? I'm confused about what's going on here. Otherwise I think we are in pretty good shape

**Pull request merged**
