### PR TITLE
Fix model signal bug

### PR DESCRIPTION
**Pull request by jdtheiss**
The model signal function had a bug where the sigma squared variable was calculated as the complete sum of squares instead of across the first dimension. This has been fixed and the poly drift function has been included (with tests).

### CODE REVIEW

**Comment by jdtheiss** [comment]
Ok, we need to add skimage to our requirements in order to use the threshold_otsu funciton. I can add that now.

**Comment by jdtheiss** [comment]
Aha, skimage is installed as scikit-image... https://bic-berkeley.github.io/psych-214-fall-2016/arteries_exercise.html?highlight=skimage

**Comment by jdtheiss** [comment]
@joewiner I think you need to update your slice timing test by replacing slice_timing_corr.slice_timing_corr with just slice_timing_corr since it imports the function directly.

**Comment by joewiner** [comment]
The test was updated in the pull request you just merged, so this error shouldn't be happening if it runs the current version

**Comment by jdtheiss** [comment]
Ok, thanks. I've also removed the unrelated commits that were errantly included in this pull request.

**Comment by joewiner** [comment]
It looks like there's an error with stacking columns in test_create_design_matrix.py. Are there potential cases where the number of outliers might result in the matrices being different sizes so that np.column_stack doesn't work? If this isn't relevant to real data, maybe change the test code?

**Comment by jdtheiss** [comment]
Yes, I think it has to do with the random values being used. I'm going to make sure there is a random seed so it should be the same each time.

**Comment by joewiner** [comment]
It looks like the poly_drift function isn't in the current version of model_signal but I know you mentioned including it at some point - maybe you haven't committed this version yet?

**Comment by jdtheiss** [comment]
Aghhhhhh, this is driving me crazy.

**Comment by jdtheiss** [comment]
This pull request is obviated by the other ones I've made last night.

**Pull request closed without merging**
