### PR TITLE
Adding presentation notes and methods

### PR DESCRIPTION
**Pull request by joewiner**
Matthew suggested this was a way to add notes to the project. If anyone has other notes they'd like to include, lets put them in this folder.

### CODE REVIEW

**Comment by jdtheiss** [comment]
Ok, that's a great idea. Is it normal to have the text look that way or is it possible to use simple text for clarity?

**Comment by joewiner** [comment]
Good point. I replaced the files with plain text

**Comment by jdtheiss** [comment]
Cool, thanks. I think you might need to git rm the .rtf files as well.

**Comment by joewiner** [comment]
👌

**Comment by jdtheiss** [comment]
Looks great, thanks!

**Pull request merged**
