### PR TITLE
Adding slice timing code and test

### PR DESCRIPTION
**Pull request by joewiner**
Here is a draft of the slice timing correction code. The test creates random 4D data and puts it through. I've also tried it with real data and I think it is working...

### CODE REVIEW

**Comment by joewiner** [comment]
I'm not sure what it means that this has failed Travis's checks... can anyone explain the issue?

**Comment by jdtheiss** [comment]
So I think the issue is that you didn't import the function you were testing (i.e. slice_timing_corr) in the test file.

**Comment by matthew-brett** [comment]
Hi Joe - it's a bit confusing because there is a `joe-branch` in the main repo (this one) as well as on your fork.  I suggest that you delete `joe-branch` in this repo, to keep things clean, and just use the version in your own fork.   Also, remember to use a new branch for each feature, so use something like `add-slice-timing` for a branch name when you start the work.

I think Justin's right about the current test failure.  If you click on the "Details" link for the test failure on the github PR web-page, you should get to this build : https://travis-ci.org/psych-214-fall-2016/project-blue/jobs/177989920#L212  .  The problem is indeed that you need to import your new function into the test module.

Keep the questions coming, I'm very happy to help on technical stuff like this, as well as the brain imaging stuff.

**Comment by joewiner** [comment]
Thanks Justin and Matthew. I've deleted 'joe-branch' from the main repo.

I'm adding the line "from fmri_utils import slice_timing_corr'" although I
have a feeling we will need to do something else to add this path in
python. I'll try committing this change.

**Comment by joewiner** [comment]
Nope! Should the line be from 'fmri_utils import slice_timing_corr.slice_timing_corr' or should I call slice_timing_corr.slice_timing_corr()?

**Comment by joewiner** [comment]
ALRIGHT finally got it to work. Thanks everyone for bearing all these notifications.

**Comment by matthew-brett** [comment]
Make sure the tests pass on your machine before pushing up - it's easier to debug the tests on your own machine.   If you've followed the README instructions on your machine, then this should work on your machine, from the ``code`` directory:

```
py.test fmri_utils
```

This is the same test that travis is running.

**Pull request merged**
