### PR TITLE
FIR filter module & test code (draft)

### PR DESCRIPTION
**Pull request by joewiner**
If someone could look at this and compare to http://nipy.org/nitime/examples/filtering_fmri.html I would appreciate it - my concerns stem from the fact that the filter functions use the nifti files directly... I'm not sure that I've used the functions correctly here

### CODE REVIEW

**Comment by joewiner** [comment]
Oh also - note you'll have to install the nitime package to run this - 'pip3 install nitime'

**Comment by joewiner** [comment]
Git seems to have mixed the slice timing correction

**Comment by joewiner** [comment]
Ugh I really tried to be clean with these changes but I can't figure out how to pull request the filter code without including the slice timing code. Sorry guys. Please review the filter code and ignore the slice timing code in this pull request

**Comment by jdtheiss** [comment]
Thanks for starting this Joe. I guess we'll need to add nitime to our requirements file. Based on the nifti_from_time_series documentation, it looks like you simply need to input the data as an array, the coordinates of the time series, the time series object, and the full path for the file you want to output. 

A few things about the code:
-The filename will need to be loaded as a nibabel image before getting the data (and we'll need to import nibabel as well).
-I think the coords need to be transposed so they are (3 x number of voxels).
-Where you append _filt to filename, you'll probably want to do it differently since that would likely append as '.nii.gz_filt'.

However, I think all we really want to do is the following:
Get the unfiltered data, get the filtered data from T_fir.data, then output a filt_data variable by subtracting T_fir.dat from data. Since we're not interested in extracting specific coordinates, we should be able to use the whole data file rather than creating all of the coordinates.

**Comment by joewiner** [comment]
Hold up - Matthew’s suggested looking at this example - https://github.com/psych-214-fall-2016/fmri-designs/blob/master/fmri_designs/regressors.py#L60 <https://github.com/psych-214-fall-2016/fmri-designs/blob/master/fmri_designs/regressors.py#L60>

It’s a filter specifically for polynomial drift, and would just add a column to the design matrix. What do you think? We can discuss at our meeting today

**Comment by jdtheiss** [comment]
Sure, we could use that. Then we would just need to include that function in the model_signal module.

**Comment by joewiner** [comment]
If you think it’s easy enough to implement, I think it might be better for the project. The timeseries filter method was taking something like 10-20 minutes per nifti when I was testing it.

**Comment by jdtheiss** [comment]
Sure, I can add it in. I tested what I had suggested above, and it didn't take nearly that long. I think using the coordinates might be the issue.

**Comment by joewiner** [comment]
Closing pull request - we're going to include polynomial filter within model_signal rather than an additional preprocessing module.

**Pull request closed without merging**
